# Desactivar el servidor web
#spring.main.web-application-type=none
# Configurar para que la aplicación finalice después de ejecutar el CommandLineRunner
spring.main.lazy-initialization=true


# Configuraci�n del servidor
server.port=8080
spring.application.name=yotelollevo-api

# Mapbox
mapbox.api.token=pk.eyJ1IjoiaHVnb2gxNCIsImEiOiJjbWtlNGJqZXQwM2ozM2Vxd280ZjYwa2xpIn0.-FtOkOpjAZeA9F8tL1C_Pw
mapbox.api.geocoding.url=https://api.mapbox.com/geocoding/v5/mapbox.places
mapbox.api.directions.url=https://api.mapbox.com/directions/v5/mapbox/driving

# CORS (permitir frontend en otro puerto)
cors.allowed-origins=http://localhost:3000,http://localhost:5173

# Logs
logging.level.edu.msmk.clases=INFO
logging.level.org.springframework.web=INFO