# Desactivar el servidor web
#spring.main.web-application-type=none
# Configurar para que la aplicaci√≥n finalice despu√©s de ejecutar el CommandLineRunner
spring.main.lazy-initialization=true


# ConfiguraciÛn del servidor
server.port=8080
spring.application.name=yotelollevo-api

# Mapbox
mapbox.api.token=pk.eyJ1IjoiaHVnb2gxNCIsImEiOiJjbWtlNGJqZXQwM2ozM2Vxd280ZjYwa2xpIn0.-FtOkOpjAZeA9F8tL1C_Pw
mapbox.api.geocoding.url=https://api.mapbox.com/search/geocode/v6/forward
mapbox.api.directions.url=https://api.mapbox.com/directions/v5/mapbox/driving

# CORS (permitir frontend en otro puerto)
cors.allowed-origins=http://localhost:3000,http://localhost:5173

# Logs
logging.level.edu.msmk.clases=INFO
logging.level.org.springframework.web=INFO

# Maestro de Provincias
config.provincias={01:'ALAVA', 02:'ALBACETE', 03:'ALICANTE', 04:'ALMERIA', 05:'AVILA', 06:'BADAJOZ', 07:'BALEARES', 08:'BARCELONA', 09:'BURGOS', 10:'CACERES', 11:'CADIZ', 12:'CASTELLON', 13:'CIUDAD REAL', 14:'CORDOBA', 15:'A CORU—A', 16:'CUENCA', 17:'GIRONA', 18:'GRANADA', 19:'GUADALAJARA', 20:'GIPUZKOA', 21:'HUELVA', 22:'HUESCA', 23:'JAEN', 24:'LEON', 25:'LLEIDA', 26:'LA RIOJA', 27:'LUGO', 28:'MADRID', 29:'MALAGA', 30:'MURCIA', 31:'NAVARRA', 32:'OURENSE', 33:'ASTURIAS', 34:'PALENCIA', 35:'LAS PALMAS', 36:'PONTEVEDRA', 37:'SALAMANCA', 38:'SANTA CRUZ DE TENERIFE', 39:'CANTABRIA', 40:'SEGOVIA', 41:'SEVILLA', 42:'SORIA', 43:'TARRAGONA', 44:'TERUEL', 45:'TOLEDO', 46:'VALENCIA', 47:'VALLADOLID', 48:'BIZKAIA', 49:'ZAMORA', 50:'ZARAGOZA', 51:'CEUTA', 52:'MELILLA'}

# Archivo Tramos
app.archivo.tramos=TRAM.EMPRESA
#app.archivo.tramos=TRAM.D250630.G250702

logging.level.io.netty=ERROR
-Dio.netty.tryReflectionSetAccessible=false

# CORS Configuration
spring.web.cors.allowed-origins=http://localhost:5173
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS,PATCH
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true
spring.web.cors.max-age=3600
